//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parcial2Entities : DbContext
    {
        public parcial2Entities()
            : base("name=parcial2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INT_CLIENTES> INT_CLIENTES { get; set; }
        public virtual DbSet<LABORATORIOS> LABORATORIOS { get; set; }
        public virtual DbSet<RECEPCION> RECEPCION { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VW_REGISTRO> VW_REGISTRO { get; set; }
    }
}
