//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCION
    {
        public int RecId { get; set; }
        public Nullable<int> CliRut { get; set; }
        public Nullable<int> LabId { get; set; }
        public Nullable<int> RecFolio { get; set; }
        public Nullable<System.DateTime> RecFechaRecepcion { get; set; }
        public Nullable<System.DateTime> RecFechaEntrega { get; set; }
        public string RecLocalidad { get; set; }
        public Nullable<int> RecCantidadMuestras { get; set; }
    
        public virtual INT_CLIENTES INT_CLIENTES { get; set; }
        public virtual LABORATORIOS LABORATORIOS { get; set; }
    }
}
